//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string ItCode { get; set; }
        public string ItDesc { get; set; }
        public decimal ItRate { get; set; }
        public int SuplNo { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
